<?php

namespace zaboy\res\NameSpase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 16:19:25.
 */
class NameOfClassTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var NameOfClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NameOfClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1, 2) == 3.
     *
     * @covers zaboy\res\NameSpase\NameOfClass::sumAB
     */
    public function testSumAB() {
        $this->assertEquals(
                3
                , $this->object->sumAB(1, 2)
        );
    }

}
